services:
  nmf:
    build: .
    container_name: nmf
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    entrypoint: python src/main.py --L 10 --M 5 --N 10 --n_iteration 100 --divergence EU
